# Import Beautiful-Jekyll Theme
remote_theme: daattali/beautiful-jekyll@5.0.0

# Name of site
title: Home

# Author
author: Trevor Nishida

# --- List of links in the navigation bar --- #
navbar-links:
  CV: "cv"
  ABOUT ME: "about"
  PROJECTS: "projects"
  GALLERY: "gallery"
  
# --- Change avatar image --- #
#avatar: "/assets/images/test.jpg"

# --- Footer social media links --- #
social-network-links:
  email: "trevords@hawaii.edu"
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
  github: trevornishida
  twitter: trevornishida
  linkedin: trevornishida

# --- General Options --- #
# Link to website in footer
url-pretty: "trevornishida.com"


# --- Colours / background image --- #

# Colours for website. Only Valid CSS colors.

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

#Images instead of colors.

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/images/coral1.JPG"

description: A personal site to host my HTML documents.
baseurl: ""
twitter_username: trevornishida
github_username: trevornishida

# --- No touchy-touchy --- #

# Output options (more information on Jekyll's site)
timezone: "Pacific/Honolulu"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap


