#theme: jekyll-theme-minimal
title: Trevor Nishida
description: A personal site to host my HTML documents.
baseurl: ""
twitter_username: trevornishida
github_username: trevornishida
remote_theme: daattali/beautiful-jekyll@5.0.0

